# Generated by Django 2.0.3 on 2018-03-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_remove_content_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='page',
            field=models.IntegerField(),
        ),
    ]
